# Generated by Django 3.0.7 on 2020-06-27 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('studentname', models.CharField(default='name', max_length=25)),
                ('studentsurname', models.CharField(default='surname', max_length=25)),
                ('studentgroup', models.CharField(choices=[('CSc', 'Computer Science'), ('SE', 'Software engineering'), ('BDA', 'Big Data'), ('MT', 'Media Tech'), ('IA', 'Industrial automation'), ('ITM', 'IT Management'), ('CS', 'Cyber security')], default='choose', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
