# Generated by Django 3.0.7 on 2020-06-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentsurname',
        ),
    ]
