# Generated by Django 3.0.7 on 2020-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200710_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_user',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('club', 'club')], default='teacher', max_length=7),
        ),
    ]
